### ISSUE TITLE
Use asyncio.Event object to break the loop on endless commands

### ISSUE THREAD

**Issue by 07734willy** [pritam42069/yadps-chan#10]
For commands such as `Reminders`, the bot loops endlessly doing a task, unable to be canceled:

https://github.com/pritam42069/yadps-chan/blob/62925f9c3d7a7a431efc3ebaceae095bcbb6ab5a/handler/commands/cogs/admin/reminders.py#L40-L42

Use an [asyncio.Event](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Event) to break out of the loop, using a corresponding command that `.set()`s the Event, and the looping over `while not exit_loop_event.is_set():` (rename that variable) breaks.

**Comment by siddhantkumar42** [comment]
Fixed in [this](https://github.com/pritam42069/yadps-chan/commit/b7111ff3243102ff2392ee0a00dc3053c9dc3137)
