### ISSUE TITLE
Parse tags and add to slash command options

### ISSUE THREAD

**Issue by 07734willy** [pritam42069/yadps-chan#12]
In the Tags command, the tags config file is re-sourced every time the command is ran. 
https://github.com/pritam42069/yadps-chan/blob/62925f9c3d7a7a431efc3ebaceae095bcbb6ab5a/handler/commands/cogs/user/tag.py#L24-L44
Instead, the bot should read the config file once, on startup, and save this somewhere. In the process of doing so, it can register each tag [as a slash command Option](https://github.com/pritam42069/yadps-chan/blob/62925f9c3d7a7a431efc3ebaceae095bcbb6ab5a/handler/commands/cogs/user/tag.py#L25) so the slash command can autocomplete the tag.

**Comment by siddhantkumar42** [comment]
added in [this](https://github.com/pritam42069/yadps-chan/commit/4532e60add0cfe7ddaf77a31b8be33522cb522b9)
