### ISSUE TITLE
Remove python 3.10 EXACTLY requirement

### ISSUE THREAD

**Issue by 0xdeadbad** [pritam42069/yadps-chan#25]
There's nothing that actually requires python 3.10 for the bot to work properly. If there is a reason for that just elaborate, otherwise it's just a hassle. 
I suggest to change the following line in the `main.py`:
`if sys.version_info[0:2] != (3, 10):`
to:
`if sys.version_info[0] != 3 and sys.version_info[1] < 5:`
or
`if sys.version_info[0] != 3 and sys.version_info[1] < 8:`

**Comment by alchemicalkube** [comment]
The reason it's included, is because this repo is a fork of mine which has it mentioned, and there's future changes coming that will rely on 3.10. Feel free to change it now and open a PR, but it will only get changed back in the future.
