### ISSUE TITLE
Move data validation from unittests to bot startup

### ISSUE THREAD

**Issue by 07734willy** [pritam42069/yadps-chan#4]
The configuration data validation should probably be done on bot startup rather than just when running unittests. There are two major reasons that I can see behind this:

- Unittest may not be reran between config changes, and if there's an invalid value, it may not be immediately obvious what's wrong, since validation didn't happen.
- The validation logic itself needs unit tested

In fact, there's a bug in the validation logic in test_actions L20: we get `TOKEN` before checking if it exists, so it will always error and exit prior to logging. https://github.com/pritam42069/yadps-chan/blob/62925f9c3d7a7a431efc3ebaceae095bcbb6ab5a/test/test_actions.py#L20

Rest of the relevant code:
https://github.com/pritam42069/yadps-chan/blob/62925f9c3d7a7a431efc3ebaceae095bcbb6ab5a/test/test_actions.py#L17-L74

**Comment by alchemicalkube** [comment]
Logic testing the code I think should be moved to it's own issue, the main functionality wanted from this issue is included in the recent commit however.
