### ISSUE TITLE
Switch to context-free logging

### ISSUE THREAD

**Issue by 07734willy** [pritam42069/yadps-chan#5]
Currently logging is created with a custom `Log` object that re-inits the logging / formatting, and may get accidentally garbage collected. Instead, we should use a more-or-less standard approach of configuring the root logger, and within each file to perform logging, create a new global logger.

In detail, this means taking the existing logging config logic:
https://github.com/pritam42069/yadps-chan/blob/62925f9c3d7a7a431efc3ebaceae095bcbb6ab5a/handler/logging/log.py#L5-L19

And putting that in an `init_logging` method, utilizing [python's logging.basicConfig](https://docs.python.org/3/library/logging.html#logging.basicConfig). 

Then in each file to do logging, at the top (just after the imports) do:

```python
from logging import getLogger
logger = getLogger(__name__)
```
and use it as
```python
logger.info(msg)
```
This will implicitly forward log records to the root logger, using its handlers, formatters, and everything else.

**Comment by alchemicalkube** [comment]
This should ideally be completed before #6, however #6 isn't a major change so likely to happen.
