### ISSUE TITLE
Resolve potential name conflicts in config

### ISSUE THREAD

**Issue by 07734willy** [pritam42069/yadps-chan#8]
In the current code for reading the config data, we can run into name conflicts:
https://github.com/pritam42069/yadps-chan/blob/62925f9c3d7a7a431efc3ebaceae095bcbb6ab5a/handler/config/data.py#L46-L59
This will silently override the other value, causing hard-to-debug errors. Apart from completely rehashing how configs are read / accessed, I think the best solution i just to keep the nesting, but maybe translating dictionary keys to object attributes, so instead of:
```python
config["field"]["subfield"]
```
We get:
```python
config.field.subfield
```
This can be accomplished two ways:
- hijacking `__getattr__` to return values from the inner dictionary instead of raising an `AttributeError`
- updating `__dict__` with the values for the attributes
Either approach will need to be done recursively, to handle nested dictionaries in the YAML config.

**Comment by alchemicalkube** [comment]
I have reworked the data class (again) considering this input was extremely valuable.

I've gone with the approach via ``__dict__`` at the moment as it's the simplest approach for the project.
```python
    def read(self):
        with open(self.yaml_file) as stream:
            y_dict = yaml.safe_load(stream)
            for block in y_dict:
                for key, value in zip(y_dict[block].keys(), y_dict[block].values()):
                    setattr(self, key, value)
            env = dotenv.dotenv_values(self.envFile)
            for v in self.env_keys:
                setattr(self, v.lower(), env.get(v.upper()))
```
Huge contrast in the difference. I have a fully converted and working version of this on my side, which I will be pushing soon so if anyone wants to get their stuff pushed before I add it in, now would be the time.

**Comment by alchemicalkube** [comment]
Further feedback from @07734willy, helping simplify things even more! 
```python
def read(self):
        with open(self.yaml_file) as stream:
            y_dict = yaml.safe_load(stream)
            for block in y_dict.values():
                for key, value in block.items():
                    setattr(self, key, value)
            env = dotenv.dotenv_values(self.envFile)
            for v in self.env_keys:
                setattr(self, v.lower(), env.get(v.upper()))
```

**Comment by alchemicalkube** [comment]
Will be in the next commit, likely upgrading to 0.0.6!
